site_name: My Blogs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  #- meta
  - search
  - tags
  - blog
  - blog:
      blog_dir: blog
      blog_toc: true
      archive: true
      archive_toc: true
      authors: true
      categories_allowed:
        - General
        - Search
        - Performance
      authors_file: .authors.yml

nav:
  - Blog:
    - blog/index.md 
    - blog/posts/hello-word.md 
